fasta_ftp:
    ftp://ftp.ensembl.org/pub/release-96/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
fasta_reference:
    Homo_sapiens.GRCh38.cdna.all.fa
    
sample:
    PBS_1:
        - /pub/raw-data/downsampled/dSRR7451187_1.fastq.gz
        - /pub/raw-data/downsampled/dSRR7451187_2.fastq.gz
    PBS_2: 
        - /pub/raw-data/downsampled/dSRR7451179_1.fastq.gz
        - /pub/raw-data/downsampled/dSRR7451179_2.fastq.gz
    EGF_1:
        - /pub/raw-data/downsampled/dSRR7451182_1.fastq.gz
        - /pub/raw-data/downsampled/dSRR7451182_2.fastq.gz
    EGF_2:
        - /pub/raw-data/downsampled/dSRR7451201_1.fastq.gz
        - /pub/raw-data/downsampled/dSRR7451201_2.fastq.gz
